name: Spell Check
on: [push] 

jobs:
  spellcheck:
    name: Spell Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run spellcheck
        uses: rojopolis/spellcheck-github-actions@0.41.0
        with:
          config_path: .github/spellcheck-config.yml
      